title: "初の心's Blog"
description: "我的个人网站"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
author:
  name   : "初の心"
  avatar : "/assets/images/avatar.png"
  bio    : "高中生 | 音乐 | 宅"
  location : "USA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mgsb4444"
excerpt: false
